# Generated by Django 5.1.3 on 2024-12-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
