# Generated by Django 5.1.3 on 2024-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySch', '0007_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
