# Generated by Django 5.1.3 on 2024-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySch', '0008_alter_teacher_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='identity',
            field=models.CharField(max_length=100),
        ),
    ]
