# Generated by Django 5.1.3 on 2024-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySch', '0009_alter_teacher_address_alter_teacher_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='math', max_length=15),
            preserve_default=False,
        ),
    ]
