# Generated by Django 5.1.3 on 2024-12-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySch', '0013_studentauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAuth',
        ),
    ]
